name: tide-ide
version: 2.0.0
grade: stable
confinement: classic
base: core22
summary: The modern approach to WebAssembly development & more
description: |
  Develop and build WebAssembly code directly on your favorite tablet device!
  Welcome to Tide, the touch-friendly IDE for WebAssembly development.

  Common Features:
  - On-device compilation & execution of WebAssembly
  - Supports C, C++23 & Python 3.11
  - Import projects from third-party software like Working Copy
  - Project-wide Find & Replace
  - Syntax highlighting

  For C/C++:
  - Debugging with breakpoints & single-stepping, call stack and stack frame information
  - Format your code based on popular styling
  - Autocomplete your variables & functions/methods
  - Project management (using a subset of QMake)
  - Optional WASI threading and socket support
  - Easily release your WebAssembly builds

  Special to Linux:
  - Ability to build Linux Snap packages when `snapcraft` is also installed

  Copyright notices:
  - LLVM: Apache 2.0 License with LLVM exceptions
  - WAMR: Apache 2.0
  - Wasi SDK: Apache 2.0
  - libqmakeparser: BSD 3-Clause License
  - no_system: BSD 3-Clause License
  - Tide icon: Parmjot Singh

architectures:
  - build-on: [amd64]
    build-for: [amd64]
  - build-on: [arm64]
    build-for: [arm64]

apps:
  tide-ide:
    command-chain: [ bin/desktop-launch ]
    command: usr/bin/tide-ide

package-repositories:
  - type: apt
    ppa: tobhe/asahi-snap-dependencies

parts:
  bootstrap:
    plugin: cmake
    source: 3rdparty
    build-attributes:
      - enable-patchelf
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - dpkg-dev
      - libssl-dev
      - libcrypt-dev
      - curl
      - clang
      - libicu-dev
    stage-packages:
      - libpcre2-16-0
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      bash -x bootstrap.sh --linux-snap

  deps:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-snaps:
      - kde-qt6-sdk
    stage-packages:
      - libpcre2-16-0
      - libpcre3
      - libssl3
      - openssl
      - fonts-open-sans
      - fonts-ubuntu
      - libgl1-mesa-dri
      - libedit2
      - libegl1
      - libffi8
      - zlib1g
      - mime-support
      - shared-mime-info
    stage:
      - usr/lib
    prime:
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    override-prime: |
      craftctl default
      update-mime-database ${CRAFT_PART_INSTALL}/usr/share/mime
      mkdir -p ${CRAFT_PRIME}/usr/share/mime
      cp -a ${CRAFT_PART_INSTALL}/usr/share/mime ${CRAFT_PRIME}/usr/share/
    after: [ bootstrap ]

  tide:
    plugin: cmake
    source: .
    build-attributes:
      - enable-patchelf
    build-environment:
      - LD_LIBRARY_PATH: /snap/kde-qt6-sdk/current/usr/lib:/snap/kde-qt6-sdk/current/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:/snap/kde-qt6-sdk/current/lib/${SNAPCRAFT_ARCH_TRIPLET}
    cmake-parameters:
      - -DCMAKE_C_COMPILER=clang
      - -DCMAKE_CXX_COMPILER=clang++
      - -DCMAKE_PREFIX_PATH=/snap/kde-qt6-sdk/current/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/cmake/Qt6
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DSNAP=1
      - -DSNAP_STAGE=$CRAFT_STAGE
    build-snaps:
      - kde-qt6-sdk
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - dpkg-dev
      - libssl-dev
      - libcrypt-dev
      - curl
      - clang
      - libgl-dev
      - libgles-dev
      - libpcre2-16-0
      - libudev-dev
      - zlib1g-dev
    after: [ deps ]

  launcher:
    plugin: dump
    source: snap/local
    organize:
      desktop-launch: bin/desktop-launch

  cmake:
    plugin: cmake
    source: 3rdparty/CMake
    build-attributes:
      - enable-patchelf
    override-build: |
      mkdir $SNAPCRAFT_PART_BUILD || true
      cd $SNAPCRAFT_PART_BUILD
      cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_C_FLAGS="-fPIC" -DCMAKE_CXX_FLAGS="-fPIC" $SNAPCRAFT_PART_SRC
      export LD_LIBRARY_PATH=${SNAPCRAFT_STAGE}/usr/lib
      ninja
      DESTDIR=$SNAPCRAFT_PART_INSTALL ninja install
    override-stage: |
      cd $SNAPCRAFT_PART_BUILD
      DESTDIR=$SNAPCRAFT_STAGE ninja install
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - dpkg-dev
    stage:
      - usr/*

  ninja:
    plugin: cmake
    source: 3rdparty/ninja
    build-attributes:
      - enable-patchelf
    override-build: |
      mkdir $SNAPCRAFT_PART_BUILD || true
      cd $SNAPCRAFT_PART_BUILD
      cmake -GNinja -DCMAKE_INSTALL_PREFIX=/usr $SNAPCRAFT_PART_SRC
      export LD_LIBRARY_PATH=${SNAPCRAFT_STAGE}/usr/lib
      ninja
      DESTDIR=$SNAPCRAFT_PART_INSTALL ninja install
    override-stage: |
      cd $SNAPCRAFT_PART_BUILD
      DESTDIR=$SNAPCRAFT_STAGE ninja install
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - dpkg-dev
    stage:
      - usr/*
