name: tide-ide
version: 2.4.0
grade: stable
confinement: classic
base: core24
summary: The modern approach to WebAssembly development & more
description: |
  Develop and build WebAssembly code directly on your favorite tablet device!
  Welcome to Tide, the touch-friendly IDE for WebAssembly development.

  Common Features:
  - On-device compilation & execution of WebAssembly
  - Supports C, C++23 & Python 3.11
  - Import projects from third-party software like Working Copy
  - Project-wide Find & Replace
  - Syntax highlighting

  For C/C++:
  - Debugging with breakpoints & single-stepping, call stack and stack frame information
  - Format your code based on popular styling
  - Autocomplete your variables & functions/methods
  - Project management (using a subset of QMake)
  - Optional WASI threading and socket support
  - Easily release your WebAssembly builds

  Special to Linux:
  - Ability to build Linux Snap packages when `snapcraft` is also installed
  - Ability to build Ubuntu Touch packages when `clickable` is also installed

  Copyright notices:
  - LLVM: Apache 2.0 with LLVM exceptions
  - WAMR: Apache 2.0
  - Wasi SDK: Apache 2.0
  - libqmakeparser: BSD 3-Clause License
  - no_system: BSD 3-Clause License
  - Tide icon: Parmjot Singh

platforms:
  arm64:
    build-on: [ arm64 ]
  amd64:
    build-on: [ amd64 ]

apps:
  tide-ide:
    command-chain: [ bin/desktop-launch ]
    command: usr/bin/tide-ide

package-repositories:
  - type: apt
    url: http://repo.ubports.com/
    key-id: B551C909D750AA744948E9ED4BD4B4D6DBB583F1
    components: [ main ]
    suites: [ 24.04-2.x ]

parts:
  builddeps:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-packages:
      - ninja-build
      - cmake
      - cmake-data
      - cmake-extras
  llvm:
    plugin: cmake
    source: 3rdparty/llvm
    build-attributes:
      - enable-patchelf
    build-packages:
      - cmake
      - ccache
      - ninja-build
      - build-essential
      - dpkg-dev
      - libssl-dev
      - libcrypt-dev
      - curl
      - clang
      - libicu-dev
    stage-packages:
      - libpcre2-16-0
    override-build: |
      cd $CRAFT_PART_SRC
      bash -x bootstrap-linux.sh
    prime:
      - usr/bin
      - usr/lib
  bootstrap:
    after: [ builddeps, llvm ]
    plugin: cmake
    source: 3rdparty
    build-packages:
      - build-essential
      - dpkg-dev
      - libssl-dev
      - libcrypt-dev
      - curl
      - libicu-dev
    stage-packages:
      - libpcre2-16-0
    override-build: |
      cd $CRAFT_PART_SRC
      bash -x bootstrap.sh --linux-snap
  deps:
    plugin: nil
    build-attributes:
      - no-patchelf
    stage-packages:
      - libpcre2-16-0
      - libpcre3
      - libssl3
      - openssl
      - fonts-open-sans
      - fonts-ubuntu
      - libedit2
      - libffi8
      - libglib2.0-0
      - zlib1g
      - shared-mime-info
      - xdg-utils
  qt6virtualkeyboard:
    plugin: cmake
    source: https://github.com/qt/qtvirtualkeyboard.git
    source-branch: 6.8.2
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_RPATH=\$ORIGIN/$CRAFT_ARCH_TRIPLET_BUILD_FOR:/snap/core24/current/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -DQT_NO_PACKAGE_VERSION_CHECK=TRUE
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$CRAFT_STAGE/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - dpkg-dev
      - qt6-svg-dev
      - qt6-base-private-dev
    stage-packages:
      - libqt6opengl6
      - libopengl0
    override-build: |
        craftctl default
        make install
        exit 0
    stage:
      - usr/*
    after: [ deps ]
  tide:
    plugin: cmake
    source: .
    build-attributes:
      - enable-patchelf
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_STAGE/usr/lib:$CRAFT_STAGE/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:$CRAFT_STAGE/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}
    cmake-parameters:
      - -DCMAKE_C_COMPILER=clang
      - -DCMAKE_CXX_COMPILER=clang++
      - -DCMAKE_PREFIX_PATH=${CRAFT_STAGE}/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/cmake/Qt6
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DSNAP=1
      - -DSNAP_STAGE=$CRAFT_STAGE
    build-packages:
      - cmake
      - ninja-build
      - build-essential
      - dpkg-dev
      - libssl-dev
      - libcrypt-dev
      - curl
      - clang
      - libgl-dev
      - libgles-dev
      - libpcre2-16-0
      - libudev-dev
      - zlib1g-dev
      - qt6-tools-dev
      - qt6-tools-dev-tools
      - qt6-declarative-dev
    after: [ llvm, bootstrap, qt6virtualkeyboard ]
  launcher:
    plugin: dump
    source: snap/local
    organize:
      desktop-launch: bin/desktop-launch
    build-attributes:
      - no-patchelf
    stage-packages:
      - qml6-module-qtquick
      - qml6-module-qtquick-controls
      - qml6-module-qtquick-effects
      - qml6-module-qtquick-layouts
      - qml6-module-qt-labs-settings
      - qml6-module-qtquick-controls2-suru
      - qt6-wayland
      - qtubuntu-qt6
      - maliit-inputcontext-qt6
      - libqt6sql6
      - libqt6widgets6
      - libqt6sql6-sqlite
  #patches:
  #  plugin: dump
  #  source: snap/patches
  #  override-prime:
  #    rm -f $CRAFT_STAGE/*.patch
  #    craftctl default
  # Special to Snapcraft release: Homebrew PSP
  #pspgcc:
  #  #after: [ patches ]
  #  plugin: nil
  #  source: https://github.com/pspdev/gcc.git
  #  source-branch: allegrex-v13.2.0
  #  build-attributes:
  #    - enable-patchelf
  #  build-packages:
  #    - libgmp-dev
  #    - libmpfr-dev
  #    - libmpc-dev
  #    - flex
  #    - bison
  #  stage-packages:
  #    - libgmp10
  #    - libmpfr6
  #    - libmpc3
  #  override-build: |
  #    cd $CRAFT_PART_BUILD
  #    export LD_LIBRARY_PATH=${CRAFT_STAGE}/usr/lib
  #    export PATH=$CRAFT_STAGE/usr/bin:$CRAFT_STAGE/bin:$PATH
  #    # patch -p1 < $CRAFT_STAGE/gcc-9.3.0-PSP.patch
  #    ./configure --quiet --prefix=/usr --target=psp --enable-languages="c,c++" \
  #      --with-float=hard  --with-newlib --disable-libssp --disable-multilib \
  #      --enable-cxx-flags="-G0" --enable-threads=posix
  #    make -j$(nproc --all)
  #    craftctl default
  #  override-stage: |
  #    cd $CRAFT_PART_BUILD
  #    DESTDIR=$CRAFT_STAGE make install
  #    craftctl default
  #pspsdk:
  #  after: [ pspgcc ]
  #  plugin: nil
  #  source: https://github.com/pspdev/pspsdk.git
  #  build-attributes:
  #    - enable-patchelf
  #  build-packages:
  #    - build-essential
  #    - dpkg-dev
  #  override-build: |
  #    cd $CRAFT_PART_BUILD
  #    export LD_LIBRARY_PATH=${CRAFT_STAGE}/usr/lib
  #    export PATH=$CRAFT_STAGE/usr/bin:$CRAFT_STAGE/bin:$PATH
  #    ./bootstrap
  #    ./configure --with-pspdev --prefix=/usr
  #    make -j$(nproc)
  #    craftctl default
  #  override-stage: |
  #    cd $CRAFT_PART_BUILD
  #    DESTDIR=$CRAFT_STAGE make install
  #    craftctl default
  cleanup:
    after: [ launcher, tide, deps ]
    plugin: nil
    override-prime: |
      set -eux

      # Clang
      rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/libclang*.so*
      rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/libLLVM-*.so*

      # Static libraries not used
      rm -f $CRAFT_PRIME/usr/lib/*.a

      # GL & docs
      rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/libEGL*.so*
      rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/libGL*.so*
      rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/libdrm*.so*
      rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/libgbm*.so*
      rm -f $CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/libvulkan.so*
      rm -fr "$CRAFT_PRIME/usr/lib/${CRAFT_ARCH_TRIPLET}/dri"
      for CRUFT in bug drirc.d glvnd libdrm lintian man; do
          rm -rf "$CRAFT_PRIME/usr/share/$CRUFT"
      done
  interpreter:
    after: [ cleanup ]
    plugin: nil
    build-packages:
      - patchelf
    override-prime: |
      set -ux
      set +e

      LD=""
      if [ "$CRAFT_ARCH_BUILD_FOR" = "amd64" ]; then
        LD="ld-linux-x86-64.so.2"
      elif [ "$CRAFT_ARCH_BUILD_FOR" = "armhf" ]; then
        LD="ld-linux-armhf.so.3"
      elif [ "$CRAFT_ARCH_BUILD_FOR" = "arm64" ]; then
        LD="ld-linux-aarch64.so.1"
      elif [ "$CRAFT_ARCH_BUILD_FOR" = "ppc64el" ]; then
        LD="ld64.so.2"
      else
        echo "Unknown architecture: $CRAFT_ARCH_BUILD_FOR"
        exit 1
      fi
      #cd $CRAFT_PRIME/usr/qml
      #for f in $(find . -name "lib*.so"); do
      #  patchelf --set-interpreter "/snap/core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/$LD" "$f" || true
      #done
      #cd $CRAFT_PRIME/usr/plugins
      #for f in $(find . -name "lib*.so"); do
      #  patchelf --set-interpreter "/snap/core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/$LD" "$f" || true
      #done
      cd $CRAFT_PRIME/usr/lib
      for f in $(find $CRAFT_ARCH_TRIPLET_BUILD_FOR -name "libQt*.so.6.*.*"); do
        patchelf --set-interpreter "/snap/core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/$LD" "$f"
      done
      for f in $(find $CRAFT_ARCH_TRIPLET_BUILD_FOR/qt6/plugins -name "*.so"); do
        patchelf --set-interpreter "/snap/core24/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/$LD" "$f"
      done
      exit 0
